name: workoutapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - assets/images/Enrollment Pic.png
    - assets/images/lock.png
    - assets/images/mail.png
    - assets/images/facebook.png
    - assets/images/user.png
    - assets/images/workout1.png
    - assets/images/goal.png
    - assets/images/calendar.png
    - assets/images/height.png
    - assets/images/scale.png
    - assets/images/notification.png
    - assets/images/default_user.png
